apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mxl-srt-gateway
  labels:
    app.kubernetes.io/name: mxl-srt-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mxl-srt-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
